### ISSUE TITLE
Snapshot error

### ISSUE THREAD

**Issue by LyNac** [mmckechney/RingVideos#39]
Attempting to download snapshots from my Ring doorbell and got this error:
```
fail: RingVideos.RingVideoApplication[0]
      System.Net.WebException: The remote server returned an error: (404) Not Found.
         at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
         at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at KoenZomers.Ring.Api.HttpUtility.DownloadFile(Uri url, String bearerToken, Int32 timeout)
         at KoenZomers.Ring.Api.Session.GetLatestSnapshot(Int32 doorbotId)
         at KoenZomers.Ring.Api.Session.GetLatestSnapshot(Int32 doorbotId, String saveAs)
         at RingVideos.RingVideoApplication.GetSnapshot(Int32 doorbotId, String fileName) in C:\Users\mimcke\source\repos\RingVideos\RingVideos\RingVideoApplication.cs:line 194
         at RingVideos.RingVideoApplication.DownloadSnapshots(Filter filter) in C:\Users\mimcke\source\repos\RingVideos\RingVideos\RingVideoApplication.cs:line 169
         at RingVideos.RingVideoApplication.Run(Filter filter, Authentication auth) in C:\Users\mimcke\source\repos\RingVideos\RingVideos\RingVideoApplication.cs:line 145
```
It appears to be trying to access your user folder.

**Comment by mmckechney** [comment]
I know this has been around a long time, but this should work now.
