### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by Radiateurs** [mmckechney/RingVideos#50]
I get the following error when running the command with valid values. I'm running it in Windows 11, with .Net Sdk 7.0
Executed with:

`all -u <myEmail> -p <myPassword> -m 10`

Result:
```
Authenticating using provided username and password
fail: RingVideos.RingVideoApplication[0]
      KoenZomers.Ring.Api.Exceptions.AuthenticationFailedException: Authentication of the session failed
         at KoenZomers.Ring.Api.HttpUtility.FormPost(Uri url, Dictionary`2 formFields, NameValueCollection headerFields)
         at KoenZomers.Ring.Api.Session.Authenticate(String operatingSystem, String hardwareId, String appBrand, String deviceModel, String deviceName, String resolution, String appVersion, Nullable`1 appInstallationDate, String manufacturer, String deviceType, String architecture, String language, String twoFactorAuthCode)
         at RingVideos.RingVideoApplication.Authenicate(Authentication auth) in <MyPath>\RingVideos\RingVideos\RingVideoApplication.cs:line 53
         at RingVideos.RingVideoApplication.Run(Filter filter, Authentication auth) in <MyPath>\RingVideos\RingVideos\RingVideoApplication.cs:line 87
```

**Comment by dfliss** [comment]
Did this issue never get resolved?

**Comment by ironsniper1** [comment]
currently have the same issue 

Authenticating using provided username and password
Connection failed. Validate your credentials.

**Comment by CESARDELATORRE** [comment]
It works for me with these command and parameters:

all 
--username "my-email" 
--password "my-password" 
--start "1/1/2023" 
--path "C:\RING_VIDEOS_BACKUP" 

Example of execution:

![image](https://github.com/user-attachments/assets/df1f2caf-4b13-49c4-a865-136d158129d6)

**Comment by mmckechney** [comment]
Authentication has been improved some and updated to the latest Ring API so it should work for you
