### ISSUE TITLE
The request has been denied by Ring due to too many requests. Try again in a few minutes

### ISSUE THREAD

**Issue by thecbucks** [mmckechney/RingVideos#52]
RingVideos.RingVideoApplication[0]
      Querying for videos to download...
fail: RingVideos.RingVideoApplication[0]
      KoenZomers.Ring.Api.Exceptions.ThrottledException: The request has been denied by Ring due to too many requests. Try again in a few minutes.
         at KoenZomers.Ring.Api.HttpUtility.GetContents(Uri url, String bearerToken) in C:\Users\mimcke\OneDrive\source\repos\RingApi\Api\HttpUtility.cs:line 96
         at KoenZomers.Ring.Api.Session.GetDoorbotsHistory(DateTime startDate, Nullable`1 endDate, Nullable`1 doorbotId) in C:\Users\mimcke\OneDrive\source\repos\RingApi\Api\Session.cs:line 429
         at RingVideos.RingVideoApplication.Run(Filter filter, Authentication auth) in C:\Users\mimcke\OneDrive\source\repos\RingVideos\RingVideos\RingVideoApplication.cs:line 139

**Comment by mmckechney** [comment]
This is due to Ring throttling your requests. Try downloading fewer videos at a time

**Comment by mmckechney** [comment]
The latest version of the app now self-throttles so you should be able to download without having to self-limit the number
